### ISSUE TITLE
Add more prompts

### ISSUE THREAD

**Issue by Munksgaard** [Munksgaard/inquirer-rs#7]
We'd like to support at least the following (from [Inquirer](https://www.npmjs.com/package/inquirer)):
- [x] Confirm (Added in 70921806)
- [ ] Input (Tracking PR #10)
- [ ] Password
- [ ] Checkbox (Tracking issue #11)
- [ ] @killercup's proposal from #2 (perhaps as another function, in order to enable both types of prompts).
